version: '3.8'

services:  
  lead_api:
    container_name: lead_api
    build:
      context: .
      dockerfile: Dockerfile
    image: gustavosg940/lead_api:latest
    ports: 
      - "8000:8000"
    depends_on:
      - mkt_db

  mkt_db:
    container_name: mkt_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D0uGu57$
      POSTGRES_DB: mkt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: lead_frontend
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - lead_api

volumes:
  pgdata: