version: '3.8'

services:
  lead_api:
    container_name: lead-api
    build:
      context: .
      dockerfile: Dockerfile
    image: gustavosg940/lead_api:latest
    ports:
      - "8000:8000"
    depends_on:
      - mkt_db

  mkt_db:
    container_name: mkt-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D0uGu57$
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  frontend:
    container_name: lead-frontend
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - lead_api

volumes:
  mysqldata:
