name: Deploy Lead Application

on:
    push:
        branches:
            - deploy-to-ec2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t gustavosg940/lead_api .
            - name: Push Image to Docker Hub
              run: docker push gustavosg940/lead_api:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull docker image
              run: docker pull gustavosg940/lead_api:latest
            - name: Delete old container
              run: docker rm -f lead-api-contain
            - name: Run docker container
              run: docker run -d -p 800:8000 --name lead-api-container gustavosg940/lead_api