name: Deploy Lead Application

on:
    push:
        branches:
            - deploy-to-ec2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            #- name: Create .env file
              #run: echo "PORT=${{ secrets.PORT }}" >> .env
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t gustavosg940/lead_api .
            - name: Push Image to Docker Hub
              run: docker push gustavosg940/lead_api:lateste
    deploy:
        needs: build
        runs-on: 