name: Deploy Lead Application

on:
    push:
        branches:
            - deploy-to-ec2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo "PORT=${{ secrets.PORT }}"